/* Auto generated by Makefile.  Note: comments may be invalid. */
#define  SIGNATURE_000 0x1e
#define  SIGNATURE_001 0x93
#define  SIGNATURE_002 0x0b
; ***** BOOT_LOAD ********************
#define  FLASHEND 0x1FFF	// Note: Word address
#define  SRAM_START 0x0060
#define  SRAM_SIZE 512
; ***** BOOTLOADER DECLARATIONS ******************************************
